import "./globals.css";

export const metadata = {
  title: "Earth in Three.js",
  description: "Generated by Next.js and Three.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
